version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: ecommerce-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api/uploads:/app/apps/api/uploads
    env_file:
      - ./apps/api/.env

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - VITE_BASE_URL_API=${VITE_BASE_URL_API}
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    container_name: ecommerce-web
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api
