const joinPaths = (...parts: string[]) =>
  `/${parts
    .map((part) => part.replace(/^\/+|\/+$/g, ''))
    .filter(Boolean)
    .join('/')}`

export const ROUTE_SEGMENTS = {
  CALLBACK: 'callback',
  LOGIN: 'login',
  REGISTER: 'register',
  FORGOT_PASSWORD: 'forgot-password',
  RESET_PASSWORD: 'reset-password',
  VERIFY_RESULT: 'verify-result',
  RESEND_VERIFY: 'resend-verify',

  USER_HOME: 'home',
  USER_PRODUCTS: 'products',
  USER_CART: 'cart',
  USER_CHECKOUT: 'checkout',
  USER_ORDERS: 'orders',
  USER_ORDER_RESULT: 'order-result',
  USER_PROFILE: 'me',

  ADMIN_PRODUCTS: 'products',
  ADMIN_BRANDS: 'brands',
  ADMIN_CATEGORIES: 'categories',
  ADMIN_ORDERS: 'orders',
  CREATE: 'create',
  EDIT: 'edit',
  ID: ':id'
} as const

export const ROUTES = {
  HOME: '/',

  ADMIN: '/admin',
  STAFF: '/staff',
  USER: '/user',
  DASHBOARD: '/dashboard',

  AUTH: '/auth',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGET_PASSWORD: '/forgot-password',
  CHANGE_PASSWORD: '/change-password',
  RESET_PASSWORD: '/reset-password',

  CREATE_PRODUCT: '/products/create',
  PRODUCT_DETAIL: '/products/:id',
  PRODUCTS: '/products'
} as const

export const ROUTE_PATHS = {
  HOME: ROUTES.HOME,

  AUTH: ROUTES.AUTH,
  AUTH_CALLBACK: joinPaths(ROUTES.AUTH, ROUTE_SEGMENTS.CALLBACK),
  AUTH_LOGIN: joinPaths(ROUTES.AUTH, ROUTE_SEGMENTS.LOGIN),
  AUTH_REGISTER: joinPaths(ROUTES.AUTH, ROUTE_SEGMENTS.REGISTER),
  AUTH_FORGOT_PASSWORD: joinPaths(ROUTES.AUTH, ROUTE_SEGMENTS.FORGOT_PASSWORD),
  AUTH_RESET_PASSWORD: joinPaths(ROUTES.AUTH, ROUTE_SEGMENTS.RESET_PASSWORD),
  AUTH_VERIFY_RESULT: joinPaths(ROUTES.AUTH, ROUTE_SEGMENTS.VERIFY_RESULT),
  AUTH_RESEND_VERIFY: joinPaths(ROUTES.AUTH, ROUTE_SEGMENTS.RESEND_VERIFY),

  USER: ROUTES.USER,
  USER_HOME: joinPaths(ROUTES.USER, ROUTE_SEGMENTS.USER_HOME),
  USER_PRODUCTS: joinPaths(ROUTES.USER, ROUTE_SEGMENTS.USER_PRODUCTS),
  USER_PRODUCT_DETAIL: (id: string = ROUTE_SEGMENTS.ID) => joinPaths(ROUTES.USER, ROUTE_SEGMENTS.USER_PRODUCTS, id),
  USER_CART: joinPaths(ROUTES.USER, ROUTE_SEGMENTS.USER_CART),
  USER_CHECKOUT: joinPaths(ROUTES.USER, ROUTE_SEGMENTS.USER_CHECKOUT),
  USER_ORDERS: joinPaths(ROUTES.USER, ROUTE_SEGMENTS.USER_ORDERS),
  USER_ORDER_DETAIL: (id: string = ROUTE_SEGMENTS.ID) => joinPaths(ROUTES.USER, ROUTE_SEGMENTS.USER_ORDERS, id),
  USER_ORDER_RESULT: joinPaths(ROUTES.USER, ROUTE_SEGMENTS.USER_ORDER_RESULT),
  USER_PROFILE: joinPaths(ROUTES.USER, ROUTE_SEGMENTS.USER_PROFILE),

  ADMIN: ROUTES.ADMIN,
  ADMIN_PRODUCTS: joinPaths(ROUTES.ADMIN, ROUTE_SEGMENTS.ADMIN_PRODUCTS),
  ADMIN_PRODUCT_CREATE: joinPaths(ROUTES.ADMIN, ROUTE_SEGMENTS.ADMIN_PRODUCTS, ROUTE_SEGMENTS.CREATE),
  ADMIN_PRODUCT_EDIT: (id: string = ROUTE_SEGMENTS.ID) =>
    joinPaths(ROUTES.ADMIN, ROUTE_SEGMENTS.ADMIN_PRODUCTS, id, ROUTE_SEGMENTS.EDIT),
  ADMIN_BRANDS: joinPaths(ROUTES.ADMIN, ROUTE_SEGMENTS.ADMIN_BRANDS),
  ADMIN_BRAND_CREATE: joinPaths(ROUTES.ADMIN, ROUTE_SEGMENTS.ADMIN_BRANDS, ROUTE_SEGMENTS.CREATE),
  ADMIN_BRAND_EDIT: (id: string = ROUTE_SEGMENTS.ID) =>
    joinPaths(ROUTES.ADMIN, ROUTE_SEGMENTS.ADMIN_BRANDS, id, ROUTE_SEGMENTS.EDIT),
  ADMIN_CATEGORIES: joinPaths(ROUTES.ADMIN, ROUTE_SEGMENTS.ADMIN_CATEGORIES),
  ADMIN_CATEGORY_CREATE: joinPaths(ROUTES.ADMIN, ROUTE_SEGMENTS.ADMIN_CATEGORIES, ROUTE_SEGMENTS.CREATE),
  ADMIN_CATEGORY_EDIT: (id: string = ROUTE_SEGMENTS.ID) =>
    joinPaths(ROUTES.ADMIN, ROUTE_SEGMENTS.ADMIN_CATEGORIES, id, ROUTE_SEGMENTS.EDIT),
  ADMIN_ORDERS: joinPaths(ROUTES.ADMIN, ROUTE_SEGMENTS.ADMIN_ORDERS),
  ADMIN_ORDER_DETAIL: (id: string = ROUTE_SEGMENTS.ID) => joinPaths(ROUTES.ADMIN, ROUTE_SEGMENTS.ADMIN_ORDERS, id)
} as const
